class Solution {
    public int[] shortestAlternatingPaths(int n, int[][] redEdges, int[][] blueEdges) {
       // 1. Build adjacency lists for both colors
               List<Integer>[] redAdj = new ArrayList[n];
                       List<Integer>[] blueAdj = new ArrayList[n];
                               for (int i = 0; i < n; i++) {
                                           redAdj[i] = new ArrayList<>();
                                                       blueAdj[i] = new ArrayList<>();
                                                               }
                                                                       for (int[] e : redEdges) redAdj[e[0]].add(e[1]);
                                                                               for (int[] e : blueEdges) blueAdj[e[0]].add(e[1]);

                                                                                       int[] result = new int[n];
                                                                                               Arrays.fill(result, -1);

                                                                                                               // 2. Visited array for both arriving colors: [node][color] 
                                                                                                                       // color 0 = red, color 1 = blue
                                                                                                                               boolean[][] visited = new boolean[n][2];

                                                                                                                                               // Queue stores {node, color, distance} 
                                                                                                                                                       // color: 0 for Red, 1 for Blue, -1 for Start
                                                                                                                                                               Queue<int[]> queue = new LinkedList<>();
                                                                                                                                                                       queue.offer(new int[]{0, 0, 0}); // Start as if we arrived via red (to take blue next)
                                                                                                                                                                               queue.offer(new int[]{0, 1, 0}); // Start as if we arrived via blue (to take red next)
                                                                                                                                                                                       visited[0][0] = true;
                                                                                                                                                                                               visited[0][1] = true;

                                                                                                                                                                                                       while (!queue.isEmpty()) {
                                                                                                                                                                                                                   int[] curr = queue.poll();
                                                                                                                                                                                                                               int u = curr[0], color = curr[1], dist = curr[2];

                                                                                                                                                                                                                                           if (result[u] == -1) result[u] = dist;

                                                                                                                                                                                                                                                       // If last edge was Red (0), next must be Blue (1)
                                                                                                                                                                                                                                                                   if (color == 0) {
                                                                                                                                                                                                                                                                                   for (int v : blueAdj[u]) {
                                                                                                                                                                                                                                                                                                       if (!visited[v][1]) {
                                                                                                                                                                                                                                                                                                                               visited[v][1] = true;
                                                                                                                                                                                                                                                                                                                                                       queue.offer(new int[]{v, 1, dist + 1});
                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                       } 
                                                                                                                                                                                                                                                                                                                                                                                                                   // If last edge was Blue (1), next must be Red (0)
                                                                                                                                                                                                                                                                                                                                                                                                                               else {
                                                                                                                                                                                                                                                                                                                                                                                                                                               for (int v : redAdj[u]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (!visited[v][0]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           visited[v][0] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   queue.offer(new int[]{v, 0, dist + 1});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return result; 
    }
}