class Solution {
    public int[] sortItems(int n, int m, int[] group, List<List<Integer>> beforeItems) {
      int groupCount = m;
              for (int i = 0; i < n; i++) {
                          if (group[i] == -1) group[i] = groupCount++;
                                  }

                                          // 2. Initialize graphs for items and groups
                                                  List<List<Integer>> itemAdj = new ArrayList<>();
                                                          for (int i = 0; i < n; i++) itemAdj.add(new ArrayList<>());
                                                                  List<List<Integer>> groupAdj = new ArrayList<>();
                                                                          for (int i = 0; i < groupCount; i++) groupAdj.add(new ArrayList<>());

                                                                                  int[] itemInDegree = new int[n];
                                                                                          int[] groupInDegree = new int[groupCount];

                                                                                                  // 3. Build the graphs
                                                                                                          for (int i = 0; i < n; i++) {
                                                                                                                      for (int prev : beforeItems.get(i)) {
                                                                                                                                      itemAdj.get(prev).add(i);
                                                                                                                                                      itemInDegree[i]++;

                                                                                                                                                                                      if (group[prev] != group[i]) {
                                                                                                                                                                                                          groupAdj.get(group[prev]).add(group[i]);
                                                                                                                                                                                                                              groupInDegree[group[i]]++;
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                          // 4. Perform Topological Sort on Items and Groups
                                                                                                                                                                                                                                                                                  List<Integer> itemOrder = topoSort(itemAdj, itemInDegree, n);
                                                                                                                                                                                                                                                                                          List<Integer> groupOrder = topoSort(groupAdj, groupInDegree, groupCount);

                                                                                                                                                                                                                                                                                                  if (itemOrder.isEmpty() || groupOrder.isEmpty()) return new int[0];

                                                                                                                                                                                                                                                                                                          // 5. Group the sorted items
                                                                                                                                                                                                                                                                                                                  Map<Integer, List<Integer>> groupToItems = new HashMap<>();
                                                                                                                                                                                                                                                                                                                          for (int item : itemOrder) {
                                                                                                                                                                                                                                                                                                                                      groupToItems.computeIfAbsent(group[item], k -> new ArrayList<>()).add(item);
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                      // 6. Concatenate items based on the sorted group order
                                                                                                                                                                                                                                                                                                                                                              int[] result = new int[n];
                                                                                                                                                                                                                                                                                                                                                                      int idx = 0;
                                                                                                                                                                                                                                                                                                                                                                              for (int grpId : groupOrder) {
                                                                                                                                                                                                                                                                                                                                                                                          for (int item : groupToItems.getOrDefault(grpId, new ArrayList<>())) {
                                                                                                                                                                                                                                                                                                                                                                                                          result[idx++] = item;
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                      return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                              private List<Integer> topoSort(List<List<Integer>> adj, int[] inDegree, int count) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      List<Integer> order = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Queue<Integer> queue = new LinkedList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (int i = 0; i < count; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (inDegree[i] == 0) queue.offer(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  while (!queue.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              int curr = queue.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          order.add(curr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (int neighbor : adj.get(curr)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (--inDegree[neighbor] == 0) queue.offer(neighbor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return order.size() == count ? order : new ArrayList<>();  
    }
}