class Solution {
    public List<List<String>> accountsMerge(List<List<String>> accounts) {
       Map<String, String> emailToName = new HashMap<>();
               Map<String, List<String>> adj = new HashMap<>();

                       for (List<String> account : accounts) {
                                   String name = account.get(0);
                                               String firstEmail = account.get(1);
                                                           for (int i = 1; i < account.size(); i++) {
                                                                           String email = account.get(i);
                                                                                           emailToName.put(email, name);
                                                                                                           adj.computeIfAbsent(firstEmail, x -> new ArrayList<>()).add(email);
                                                                                                                           adj.computeIfAbsent(email, x -> new ArrayList<>()).add(firstEmail);
                                                                                                                                       }
                                                                                                                                               }

                                                                                                                                                       Set<String> visited = new HashSet<>();
                                                                                                                                                               List<List<String>> mergedAccounts = new ArrayList<>();

                                                                                                                                                                       for (String email : emailToName.keySet()) {
                                                                                                                                                                                   if (!visited.contains(email)) {
                                                                                                                                                                                                   List<String> component = new ArrayList<>();
                                                                                                                                                                                                                   Stack<String> stack = new Stack<>();
                                                                                                                                                                                                                                   stack.push(email);
                                                                                                                                                                                                                                                   visited.add(email);

                                                                                                                                                                                                                                                                   while (!stack.isEmpty()) {
                                                                                                                                                                                                                                                                                       String node = stack.pop();
                                                                                                                                                                                                                                                                                                           component.add(node);
                                                                                                                                                                                                                                                                                                                               for (String neighbor : adj.get(node)) {
                                                                                                                                                                                                                                                                                                                                                       if (!visited.contains(neighbor)) {
                                                                                                                                                                                                                                                                                                                                                                                   visited.add(neighbor);
                                                                                                                                                                                                                                                                                                                                                                                                               stack.push(neighbor);
                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Collections.sort(component);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           component.add(0, emailToName.get(email));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           mergedAccounts.add(component);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return mergedAccounts; 
    }
}