class Solution {
    public int orangesRotting(int[][] grid) {
      if (grid == null || grid.length == 0) return 0;
              int rows = grid.length;
                      int cols = grid[0].length;
                              Queue<int[]> queue = new LinkedList<>();
                                      int freshCount = 0;

                                              // 1. Setup initial state
                                                      for (int r = 0; r < rows; r++) {
                                                                  for (int c = 0; c < cols; c++) {
                                                                                  if (grid[r][c] == 2) {
                                                                                                      queue.offer(new int[]{r, c});
                                                                                                                      } else if (grid[r][c] == 1) {
                                                                                                                                          freshCount++;
                                                                                                                                                          }
                                                                                                                                                                      }
                                                                                                                                                                              }

                                                                                                                                                                                      // If no fresh oranges, 0 minutes have passed
                                                                                                                                                                                              if (freshCount == 0) return 0;

                                                                                                                                                                                                      int minutes = 0;
                                                                                                                                                                                                              int[][] dirs = {{1, 0}, {-1, 0}, {0, 1}, {0, -1}};

                                                                                                                                                                                                                      // 2. BFS Traversal
                                                                                                                                                                                                                              while (!queue.isEmpty()) {
                                                                                                                                                                                                                                          int size = queue.size();
                                                                                                                                                                                                                                                      boolean rottedInThisStep = false;

                                                                                                                                                                                                                                                                  for (int i = 0; i < size; i++) {
                                                                                                                                                                                                                                                                                  int[] curr = queue.poll();
                                                                                                                                                                                                                                                                                                  for (int[] d : dirs) {
                                                                                                                                                                                                                                                                                                                      int ni = curr[0] + d[0];
                                                                                                                                                                                                                                                                                                                                          int nj = curr[1] + d[1];

                                                                                                                                                                                                                                                                                                                                                              if (ni >= 0 && ni < rows && nj >= 0 && nj < cols && grid[ni][nj] == 1) {
                                                                                                                                                                                                                                                                                                                                                                                      grid[ni][nj] = 2; // Rot the orange
                                                                                                                                                                                                                                                                                                                                                                                                              queue.offer(new int[]{ni, nj});
                                                                                                                                                                                                                                                                                                                                                                                                                                      freshCount--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              rottedInThisStep = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (rottedInThisStep) minutes++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // 3. Final verification
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return freshCount == 0 ? minutes : -1;  
    }
}